#pragma once

#ifdef TARGET_MRGC_G32
#define LCD_PIN_NUM_MISO GPIO_NUM_NC
#define LCD_PIN_NUM_MOSI GPIO_NUM_23
#define LCD_PIN_NUM_CLK  GPIO_NUM_18
#define LCD_PIN_NUM_CS   GPIO_NUM_5
#define LCD_PIN_NUM_DC   GPIO_NUM_12
#define LCD_PIN_NUM_RST  -1
#define LCD_PIN_NUM_BCKL GPIO_NUM_27

#define SCREEN_OFFSET_TOP 28
#define SCREEN_WIDTH 240
#define SCREEN_HEIGHT 224
#else
#if CONFIG_HW_ODROID_GO
#define LCD_PIN_NUM_MISO GPIO_NUM_19
#define LCD_PIN_NUM_MOSI GPIO_NUM_23
#define LCD_PIN_NUM_CLK  GPIO_NUM_18
#define LCD_PIN_NUM_CS   GPIO_NUM_5
#define LCD_PIN_NUM_DC   GPIO_NUM_21
#define LCD_PIN_NUM_RST  -1
#define LCD_PIN_NUM_BCKL GPIO_NUM_14

#define SCREEN_OFFSET_TOP 0
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#else
#define LCD_PIN_NUM_MISO CONFIG_BSP_DISPLAY_MISO_GPIO
#define LCD_PIN_NUM_MOSI CONFIG_BSP_DISPLAY_MOSI_GPIO
#define LCD_PIN_NUM_CLK  CONFIG_BSP_DISPLAY_SCLK_GPIO
#define LCD_PIN_NUM_CS   CONFIG_BSP_DISPLAY_CS_GPIO
#define LCD_PIN_NUM_DC   CONFIG_BSP_DISPLAY_DC_GPIO
#define LCD_PIN_NUM_RST  CONFIG_BSP_DISPLAY_RST_GPIO
#define LCD_PIN_NUM_BCKL CONFIG_BSP_DISPLAY_BACKLIGHT_GPIO

#define SCREEN_OFFSET_TOP CONFIG_BSP_DISPLAY_VERTICAL_OFFSET
#if CONFIG_BSP_DISPLAY_ROTATION_SWAP_XY
#define SCREEN_WIDTH CONFIG_BSP_DISPLAY_HEIGHT
#define SCREEN_HEIGHT CONFIG_BSP_DISPLAY_WIDTH
#else
#define SCREEN_WIDTH CONFIG_BSP_DISPLAY_WIDTH
#define SCREEN_HEIGHT CONFIG_BSP_DISPLAY_HEIGHT
#endif
#endif
#endif

void ili9341_init(void);
void ili9341_deinit(void);
void ili9341_writeLE(const uint16_t *buffer);
void ili9341_writeBE(const uint16_t *buffer);
